### ISSUE TITLE
[Bug] Clients on 1.20.5 and 1.20.6 experience frequent disconnections for "Network Protocol Error"

### ISSUE THREAD

**Issue by deafkite42** [EarthMC/Issue-Tracker#1810]
### Server

Aurora

### Describe the bug

When using 1.20.5 or 1.20.6 clients on EMC, you will be frequently disconnected seemingly at random. This appears to be some issue with the combat tagging plugin and some incompatibility introduced in 1.20.5. See the attached stack trace below. 

### To Reproduce

1. Use a 1.20.5 or 1.20.6 client
2. Connect to EarthMC
3.  After a while, you will be disconnected for "Network Protocol Error"

### Expected behavior

1.20.5 or 1.20.6 clients should not be randomly disconnected

### Screenshots

![Screenshot_20240531_144256](https://github.com/EarthMC/Issue-Tracker/assets/51095654/b6d4e624-91b4-4ef8-a897-212cf7abba69)

### Additional context

```[14:42:44] [Render thread/ERROR]: Failed to handle packet net.minecraft.class_5900@3ba30276
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'CombatTagged'.
	at net.minecraft.class_269.method_1157(class_269.java:308) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2044) ~[client-intermediary.jar:?]
	at net.minecraft.class_5900.method_34173(class_5900.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_5900.method_11054(class_5900.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[14:42:44] [Render thread/INFO]: Stopping worker threads
[14:42:44] [Render thread/WARN]: Client disconnected with reason: Network Protocol Error
```

**Comment by deafkite42** [comment]
This may only affect Fabric clients, so far I have not had the issue on a Vanilla client

**Comment by deafkite42** [comment]
an example of this on Vanilla 1.20.6
```[15:45:02] [Render thread/ERROR]: Failed to handle packet afv@6ca146d9
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team '939F445D_AAAA20'.
	at ewx.b(SourceFile:308) ~[minecraft-1.20.6-client.jar:?]
	at fxy.a(SourceFile:2044) ~[minecraft-1.20.6-client.jar:?]
	at afv.a(SourceFile:132) ~[minecraft-1.20.6-client.jar:?]
	at afv.a(SourceFile:18) ~[minecraft-1.20.6-client.jar:?]
	at zz.a(SourceFile:25) ~[minecraft-1.20.6-client.jar:?]
	at bpm.d(SourceFile:162) [minecraft-1.20.6-client.jar:?]
	at bpq.d(SourceFile:23) [minecraft-1.20.6-client.jar:?]
	at bpm.A(SourceFile:136) [minecraft-1.20.6-client.jar:?]
	at bpm.bA(SourceFile:121) [minecraft-1.20.6-client.jar:?]
	at ffh.c(SourceFile:1275) [minecraft-1.20.6-client.jar:?]
	at ffh.f(SourceFile:888) [minecraft-1.20.6-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [minecraft-1.20.6-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[15:45:02] [Sound engine/ERROR]: Stop: Invalid name parameter.
[15:45:02] [Render thread/WARN]: Client disconnected with reason: Network Protocol Error
```

**Comment by CorruptedGreed** [comment]
Doesn't seem like it's happening anymore
